### ISSUE TITLE
”Issueベースの開発”レビュー依頼

### ISSUE THREAD

**Issue by uedaMasaya** [uedaMasaya/Population-Pop-Puzzle#8]
### 実装予定の機能
- ユーザー関係機能
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ユーザー名変更機能
- [ ] メールアドレス変更機能
- [ ] パスワード変更機能
- [ ] プロフィール画像保存・変更機能
- [ ] スコア記録機能

- 管理者関係機能
- [ ] ユーザー情報編集機能
- [ ] ユーザー削除機能

- ゲーム関係機能
- [ ] スコアランキング閲覧機能（未ログインでも閲覧可能）
- [ ] ゲームプレイ機能（未ログインでも実施可能）

### 作成ページ

- [ ]  トップページ
- [ ]  出題ページ
- [ ]  回答結果ページ
- [ ]  最終結果ページ
- [ ]  ユーザー登録ページ
- [ ]  ログインページ
- [ ]  パスワード再設定ページ
- [ ]  ユーザープロフィールページ
- [ ]  ユーザープロフィール変更ページ
- [ ]  お問い合わせページ
- [ ]  利用規約ページ
- [ ]  プライバシーポリシーページ

- [ ]  管理者：　トップページ
- [ ]  管理者：　ユーザー一覧ページ
- [ ]  管理者：　ユーザー情報編集ページ
- [ ]  管理者：　得点一覧ページ

**Comment by uedaMasaya** [comment]
# Git Hub ProjectのURL
https://github.com/users/uedaMasaya/projects/2

**Comment by Mariko222** [comment]
ご提出ありがとうございます。
下記カリキュラム内容を参考に各カードのストーリーポイントの設定をお願いします。
https://school.runteq.jp/v3/curriculums/application_development/chapters/11

**Comment by uedaMasaya** [comment]
失礼しました。
ストーリーポイントの表示が保存されていませんでした。
再度ご確認よろしくお願いいたします。

**Comment by kashiwagi-rena** [comment]
ご提出いただきありがとうございます。

> X（旧：twitter）でのログイン機能
> ログイン機能（devise）の実装

上記実装がストーリーポイント5になっております。少々大きいと感じます。また、ご自身で実装を行われる際も心身的な負担を感じられる可能性があります。
難しい実装と認識された場合、調査タスクと実装タスクに分けて実装の流れを掴んでから行ってみて下さい。(先に調べることによりストーリーポイント3の実装が想像できる通常の機能レベルのタスクにしてみて下さい。)
不透明箇所・明確箇所の可視化を行いわからないことは調べてから行うようにして下さい。

上記を行うことにより、より進捗を感じられながら開発を進められると思います。

**Comment by uedaMasaya** [comment]
ご助言ありがとうございます！
調査のissueを作成し、X（旧：twitter）でのログイン機能、ログイン機能（devise）の実装部分のストーリーポイントを少なくしました。

**Comment by tmtkzk0823** [comment]
確認しました。
> 調査のissueを作成し、X（旧：twitter）でのログイン機能、ログイン機能（devise）の実装部分のストーリーポイントを少なくしました。

上記、大丈夫そうです。

以下、追加のコメントになります。

---

- デプロイ、rails newなどのカードも作成しましょう。
- MVPは「ユーザーに必要最低限の機能を提供できること」が満たされていれば大丈夫です。この条件と考えると、ユーザーが使用しない「管理画面」の実装はMVPまでに実装は不要かと思いましたがいかがでしょうか？

**Comment by uedaMasaya** [comment]
ご確認ありがとうございます。
下記の修正を加えましたので、再度ご確認よろしくお願いいたします。
＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿
・環境構築、デプロイのIssueを追加しました。
・確かに、MVP時の要件上は、不要かと思いましたので、管理画面の実装は一旦削除しました。

**Comment by kenchasonakai** [comment]
LGTMです！
